services:
  metadata-server:
    image: hochstenbach/metadata-server:v0.0.2
    container_name: metadata-server
    ports:
      - "3001:3001"
    depends_on:
      - zotero
    networks:
      - app-network
    volumes:
      - ./metadata-server/config:/app/config
      - ./metadata-server/error:/app/error
      - ./metadata-server/inbox:/app/inbox
      - ./metadata-server/outbox:/app/outbox
    profiles:
      - metadata

  archiver-server:
    image: hochstenbach/archiver-server:v0.0.1
    container_name: archiver-server
    ports:
      - "3007:3007"
    networks:
      - app-network
    volumes:
      - ./archiver-server/error:/app/error
      - ./archiver-server/inbox:/app/inbox
      - ./archiver-server/tmp:/app/tmp
    profiles:
      - archiver
    
  zotero:
    image: hochstenbach/zotero-server:v0.0.1
    container_name: zotero-translator
    ports:
      - "1969:1969"
    networks:
      - app-network
    profiles: 
      - base

  wiki:
    image: hochstenbach/wiki-server:v0.0.1
    container_name: wiki-server
    ports:
      - "3000:3000"
    networks:
      - app-network
    profiles:
      - base

  postgres:
    image: postgres:16-bullseye
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    profiles:
      - base

  eventlog-server:
    image: hochstenbach/eventlog-server:v0.0.1
    container_name: eventlog-server
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - postgres
    ports:
      - 3003:3003
    networks:
      - app-network

  claimbot-server:
    image: hochstenbach/claimbot-server:v0.0.2
    container_name: claimbot-server
    environment:
      DEMO_MODE: NO_TOOTS
      MASTODON_URL: ${MASTODON_URL}
      MASTODON_ACCESS_TOKEN: ${MASTODON_ACCESS_TOKEN}
      WIKIJS_URL: ${WIKIJS_URL}
      WIKIJS_ACCESS_TOKEN: ${WIKIJS_ACCESS_TOKEN}
      VERIFICATION_URL: ${VERIFICATION_URL}
      VERIFICATION: loose
      POSTGRES_HOST: ${POSTGRES_HOST}
      EVENTLOG_TRACE_URL: ${EVENTLOG_TRACE_URL}
    depends_on:
      - eventlog-server
    ports:
      - 3002:3002
    networks:
      - app-network
    volumes:
      - ./claimbot-server/config/ecosystem.config.js:/app/ecosystem.config.js
      - ./claimbot-server/config:/app/config
      - ./claimbot-server/accepted:/app/accepted
      - ./claimbot-server/error:/app/error
      - ./claimbot-server/inbox:/app/inbox
      - ./claimbot-server/outbox:/app/outbox
    profiles:
      - claimbot
  
  claimlog-server:
    image: hochstenbach/rdf-generator:v0.0.2
    container_name: claimlog-server
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      CLAIMLOG_URL: ${CLAIMLOG_URL}
      METADATA_ACTOR: ${METADATA_ACTOR}
    depends_on:
      - eventlog-server
    ports:
      - 3006:3006
    networks:
      - app-network
    volumes:
      - ./claimlog-server/error:/app/error
      - ./claimlog-server/inbox:/app/inbox
      - ./claimlog-server/tmp:/app/tmp
      - ./claimlog-server/public:/app/public
    profiles:
      - claimlog

  proxy-server:
    image: nginx:alpine
    container_name: proxy-server
    ports:
      - "80:80"
    volumes:
      - ./proxy/etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro  
      - ./proxy/www:/var/www
    depends_on:
      - eventlog-server
    networks:
      - app-network 
    profiles:
      - base

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
